name: travel_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  open_file: ^3.2.1
  pdf_viewer_plugin: ^2.0.1
  flutter_carousel_slider: ^1.0.8
  responsive_framework: ^0.2.0
  flutter_launcher_icons: ^0.11.0
  animation_list: ^2.2.0
  cloud_firestore: ^4.0.4
  path_provider: ^2.0.10
  flutter_local_notifications: ^12.0.3
  dio: ^4.0.6
  gallery_saver: ^2.3.2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.2.7
  google_fonts: ^3.0.1
  badges: ^2.0.2
  video_player: ^2.4.6
  lottie: ^2.0.0
  flutter_svg: ^1.1.3
  glassmorphism: ^3.0.0
  carousel_images: ^1.1.2
  flutter_staggered_animations: ^1.0.0
  firebase_messaging: ^14.0.4
  url_launcher: ^6.1.5
  uni_links: ^0.5.1
  firebase_core: ^2.1.1
  http: ^0.13.5
  firebase_storage: ^11.0.7
  fluttertoast: ^8.1.2
  pdf: ^3.8.4

flutter_icons :
  android : true
  ios : true
  image_path: 'assets/playstore.png'
  adaptive_icon_foreground: 'assets/playstore1.png'

flutter_native_splash:
  image: assets/playstore.png
  color: "#42a5f5"
  android_gravity: fill


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/
